# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Dan's Tech (and more) Blog
name: Dan's Tech (and more) Blog
description: 
  Very infrequent posts about technology and sometimes boardgames
baseurl: /blog
github_username: DanDobrick

# Default layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# jekyll-paginate configuration
paginate: 10

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - draft_scripts.thor

include: ["_pages"]
permalink: /posts/:title/
excerpt_separator: <!--more-->
author: https://dandobrick.com/

host: 0.0.0.0
