menu: 
  - name: Posts
    link: /
  - name: Tags
    link: /tags
  - name: About
    link: /about
  - name: Contact
    link: /contact
  # - name: submenu example
  #   submenu:
  #     - name: GitHub
  #       icon: github
  #       link: http://github.com/DanDobrick
  #       external: true
  #     - name: LinkedIn
  #       icon: linkedin-square
  #       link: http://www.linkedin.com/in/DanDobrick
  #       external: true
  #     - name: Twitter
  #       icon: twitter
  #       link: https://twitter.com/DanDobrick
  #       external: true
    
