menu: 
  - name: Posts
    link: /blog/
  - name: About
    link: /blog/about
  - name: Links
    link: /blog/links
  - name: Unexplored Games
    link: https://www.unexplored-games.com/
  # - name: Contact
  #   link: /contact
  # - name: submenu example
  #   submenu:
  #     - name: GitHub
  #       icon: github
  #       link: http://github.com/DanDobrick
  #       external: true
  #     - name: LinkedIn
  #       icon: linkedin-square
  #       link: http://www.linkedin.com/in/DanDobrick
  #       external: true
  #     - name: Twitter
  #       icon: twitter
  #       link: https://twitter.com/DanDobrick
  #       external: true
    
