name: Update Profile README

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DanDobrick repo
        uses: actions/checkout@v4
        with:
          repository: DanDobrick/DanDobrick
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Update README with latest blog posts
        run: bundle exec ruby update_readme.rb

      - name: Commit and push if README changed
        run: |
          git config --global user.email "readme-bot@dandobrick.com"
          git config --global user.name "Blog README Bot"
          git diff --quiet || (git add README.md && git commit -m "Updated README with latest blog posts" && git push) 